name: Shared Build

on:
  pull_request:
    paths:
      - 'packages/shared/**'
    branches: [main, dev]

jobs:
  build-shared:
    uses: sisques-labs/workflows/.github/workflows/web-build.yml@main
    with:
      app_path: 'packages/shared'
      app_name: 'Shared Package'
      node_version: '24'
      run_lint: true
      run_test: false
      build_command: 'build'
    secrets: inherit # Required if the workflow needs secrets
