name: Web Build

on:
  pull_request:
    paths:
      - 'apps/web/**'
    branches: [main, dev]

jobs:
  build-web:
    uses: sisques-labs/workflows/.github/workflows/web-build.yml@main
    with:
      app_path: 'apps/web'
      app_name: 'My Web App'
      node_version: '24'
      run_lint: true
      run_test: true
      build_command: 'build'
    secrets: inherit # Required if the workflow needs secrets
